import { buildBusinessId } from '../utils/dedupe'
import type { Business } from '../types/business'
import { getDetailPanel, queryAttr, queryText, sleep, waitFor } from './dom'

/**
 * Parses latitude/longitude out of the Maps URL for the currently open
 * place. Google encodes the place's coordinates in the URL's data blob as
 * `!3d<lat>!4d<lng>`; the `@<lat>,<lng>,<zoom>` segment reflects the map
 * viewport center instead, which can drift from the pin once the user (or
 * Maps itself) pans — so we prefer `!3d/!4d` and only fall back to `@`.
 */
function parseCoordinatesFromUrl(href: string): { latitude: number | null; longitude: number | null } {
  const dataMatch = href.match(/!3d(-?\d+\.\d+)!4d(-?\d+\.\d+)/)
  if (dataMatch) {
    return { latitude: parseFloat(dataMatch[1]), longitude: parseFloat(dataMatch[2]) }
  }
  const centerMatch = href.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/)
  if (centerMatch) {
    return { latitude: parseFloat(centerMatch[1]), longitude: parseFloat(centerMatch[2]) }
  }
  return { latitude: null, longitude: null }
}

/** Parses "4.5" out of an aria-label like "4.5 stars" or the visible text. */
function parseRating(panel: ParentNode): number | null {
  const ariaLabel = queryAttr(panel, ['span[role="img"][aria-label*="star" i]'], 'aria-label')
  const text = ariaLabel || queryText(panel, ['span.MW4etd', 'div.F7nice span'])
  const match = text.match(/(\d+(\.\d+)?)/)
  return match ? parseFloat(match[1]) : null
}

/** Parses "1,234" -> 1234 out of a "(1,234)" review-count label. */
function parseReviewCount(panel: ParentNode): number | null {
  const text = queryText(panel, [
    'span.UY7F9',
    'div.F7nice span[aria-label*="review" i]',
    'button[aria-label*="review" i]',
  ])
  const match = text.replace(/[(),]/g, '').match(/\d+/)
  return match ? parseInt(match[0], 10) : null
}

/** Joins the open-hours table into a single readable string, e.g. "Mon: 9AM-5PM; Tue: ...". */
function parseHours(panel: ParentNode): string {
  const rows = panel.querySelectorAll('table[aria-label*="hour" i] tr, div[aria-label*="hours" i] tr')
  if (rows.length > 0) {
    const parts: string[] = []
    rows.forEach((row) => {
      const text = row.textContent?.replace(/\s+/g, ' ').trim()
      if (text) parts.push(text)
    })
    if (parts.length) return parts.join('; ')
  }
  // Fallback: a single-line hours summary Maps sometimes shows instead of a table.
  return queryText(panel, ['div[aria-label*="hours" i]', 'span.ZDu9vd'])
}

/**
 * Reads Google's short editorial "About" blurb for the business, when one
 * is shown on the page (common for chains, notable local spots, and
 * anything with a Wikipedia-sourced description). `data-attrid` is a
 * long-standing, fairly stable Google attribute pattern for this kind of
 * knowledge-panel text, used well beyond just Maps.
 */
function parseDescription(panel: ParentNode): string {
  return queryText(panel, ['div[data-attrid="description"]', 'div.WeS02d.fontBodyMedium'])
}

/**
 * Best-effort capture of Google's AI-generated review summary ("People say
 * the staff is friendly and the coffee is great...") when Maps shows one.
 *
 * This is a newer, still-rolling-out feature with no stable class name to
 * hook into, so we locate it by its "Generated by AI"-style disclaimer text
 * and read the paragraph it's attached to, rather than guessing a selector.
 * Returns '' (not an error) if no such summary is shown for this business —
 * that's the common case, not a failure.
 */
function parseReviewsSummary(panel: ParentNode): string {
  const candidates = Array.from(panel.querySelectorAll<HTMLElement>('div, span'))
  const disclaimer = candidates.find(
    (el) => /generated by ai|summarized by ai|ai summary/i.test(el.textContent ?? '') && (el.textContent?.length ?? 0) < 80,
  )
  if (!disclaimer) return ''

  // The actual summary text usually lives in the disclaimer's containing
  // block, alongside (not inside) the short disclaimer label itself.
  const container = disclaimer.closest('div')
  if (!container) return ''

  const fullText = container.textContent?.replace(/\s+/g, ' ').trim() ?? ''
  const disclaimerText = disclaimer.textContent?.replace(/\s+/g, ' ').trim() ?? ''
  const summary = fullText.replace(disclaimerText, '').trim()
  return summary.length > 10 ? summary : ''
}

/** Reads all target fields out of the place detail panel currently on screen. */
function readFieldsFromPanel(panel: HTMLElement): Omit<Business, 'id' | 'extractedAt'> {
  const name = queryText(panel, ['h1.DUwDvf', 'h1'])
  const category = queryText(panel, ['button.DkEaL', 'button[jsaction*="category"]'])
  const address = queryAttr(panel, ['button[data-item-id^="address"]'], 'aria-label').replace(/^Address:\s*/i, '')
  const phone = queryAttr(panel, ['button[data-item-id^="phone"]'], 'aria-label').replace(/^Phone:\s*/i, '')
  const website =
    queryAttr(panel, ['a[data-item-id="authority"]'], 'href') ||
    queryAttr(panel, ['a[data-item-id="authority"]'], 'aria-label').replace(/^Website:\s*/i, '')
  const { latitude, longitude } = parseCoordinatesFromUrl(location.href)

  return {
    name,
    category,
    rating: parseRating(panel),
    reviewCount: parseReviewCount(panel),
    address,
    phone,
    website,
    hours: parseHours(panel),
    latitude,
    longitude,
    description: parseDescription(panel),
    reviewsSummary: parseReviewsSummary(panel),
  }
}

/**
 * Waits for the place detail panel to finish rendering on the *current*
 * page and extracts it into a Business record.
 *
 * This assumes the browser has already navigated to the place's own URL
 * (https://www.google.com/maps/place/...) — see content.ts, which drives
 * the tab there directly rather than clicking a card in a results feed.
 * A direct page load gives every field (phone, website, hours) a single,
 * fully-rendered place page to read from, instead of a transient side
 * panel that may or may not have finished populating.
 */
export async function extractCurrentDetailPanel(): Promise<Business> {
  const panel = await waitFor(
    () => {
      const el = getDetailPanel()
      return el && el.querySelector('h1')?.textContent?.trim() ? el : null
    },
    { timeout: 15000 },
  )

  // Hours/website/phone can render a beat after the <h1> does; give the
  // panel a brief moment to finish populating before reading from it.
  await sleep(700)

  const fields = readFieldsFromPanel(panel)
  if (!fields.name) {
    throw new Error('Extraction failed: business name not found in detail panel')
  }

  return {
    id: buildBusinessId(fields.name, fields.address),
    extractedAt: new Date().toISOString(),
    ...fields,
  }
}

/** Retries extractCurrentDetailPanel with a short backoff, for transient render delays. */
export async function extractCurrentDetailPanelWithRetry(maxAttempts = 3): Promise<Business> {
  let lastError: unknown
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await extractCurrentDetailPanel()
    } catch (err) {
      lastError = err
      if (attempt < maxAttempts) await sleep(1000 * attempt)
    }
  }
  throw lastError instanceof Error ? lastError : new Error('Unknown extraction failure')
}
